### ISSUE TITLE
Are queries using indices?

### ISSUE THREAD

**Issue by LucidComplex** [realm/realm-graphql-service#32]
For example,
```gql
{
  users(query: "accounts.providerId = 'testdriver'") {
    userId
  }
}
```
Assuming there is an index on `providerId`, is it used?

**Comment by LucidComplex** [comment]
I don't quite understand, how do the indices work when they depend on the schema declaration? Doesn't it do something in the database when the schema is first pushed?

**Comment by nirinchev** [comment]
The on-device copy of the database is a fully featured Realm database (with indices, PKs and all that), that our Sync engine is keeping synchronized with the server database. The data in both is the same, but indices are not synchronized between them. The reasoning is that this gives you more flexibility to declare different indices for different applications using the same Realm - e.g. a mobile app can define an index on the `Name` property, but a desktop app, where disk space and RAM are much more abundant can declare indices on many more properties.

All this means that the local database index declarations are not synchronized across all clients opening the same Realm. And because until recently, the server didn't run any queries, it didn't make sense to create indices on the server Realm. That obviously changed with the introduction of our GraphQL API and we have plans to expose controls to add/remove indices on server side Realms, but haven't gotten around to doing it yet.

**Comment by astigsen** [comment]
Closing this as the question was answered. Please reopen if needed.
