### ISSUE TITLE
Use ISO 8601 as default returned format for dates 

### ISSUE THREAD

**Issue by pierre-moire** [realm/realm-graphql-service#89]
Currently when we query a date field from a class through GraphQL, we get something like "Wed Aug 01 2018 13:47:32 GMT+0000 (UTC)"

Is possible to return an iso 8601 date by default, or a way to specify format we would like to get?

Note: also in GraphiQL when we look at the schema of a class, dates are currently shown as strings. Shouldn't it show the proper type?

Many thanks,

Pierre

**Comment by nirinchev** [comment]
This makes sense - the reason why we chose to use `String` was because GraphQL (and json) doesn't have a built-in date type. Still, I think there's value in introducing one, which has the added benefit that it gives us control over the serialization format. I have a PR that fixes it and expect it will be released with the next version of ROS.
